modLoader="javafml"
loaderVersion="[44,)"
license="Apache License 2.0"

[[mods]]
modId="travelanchors"
version="${file.jarVersion}"
displayName="Travel Anchors"
displayURL="https://www.curseforge.com/minecraft/mc-mods/travel-anchors"
updateJSONURL="https://assets.melanx.de/updates/travel-anchors.json"
credits="MelanX and noeppi_noeppi"
authors="CastCrafter"
description='''
Adds a staff of travelling and a travel anchor to teleport around the world.
'''

[[dependencies.travelanchors]]
    modId="forge"
    mandatory=true
    versionRange="[44.1.20,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travelanchors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travelanchors]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.3-4.3.0,)"
    ordering="NONE"
    side="BOTH"
